### ISSUE TITLE
There was a problem with the installation

### ISSUE THREAD

**Issue by good-repo** [linnil1/sync-ytchat-to-discord#1]
After pip3 install -r requirements.txt
![Screenshot_20211004_121454](https://user-images.githubusercontent.com/84621585/135816750-ec2bd99b-47d7-4f79-911e-dbcb503df8eb.png)

returns ERROR: Could not open requirements file: [Errno 2]

Ubuntu 20.04 LTS

**Comment by linnil1** [comment]
Oh, there is a typo. `requirments.txt` should be `requirements.txt`
```
pip install -r requirements.txt
```

**Comment by good-repo** [comment]
Thanks, I fixed it and it worked)
I successfully launched the bot and decided to test it. Found a random stream on YouTube. I enter the commands as described in your instructions. The bot responds with OK, and then it is stopped.
Tell me am I doing something wron
![Screenshot_20211004_153429](https://user-images.githubusercontent.com/84621585/135844918-f81fea19-2c96-4c21-9bc9-9d935aec5d76.png)
g?

**Comment by good-repo** [comment]
Thanks, I fixed it and it worked)
I successfully launched the bot and decided to test it. Found a random stream on YouTube. I enter the commands as described in your instructions. The bot responds with OK, and then it is stopped.
Tell me am I doing something wron
![Screenshot_20211004_153429](https://user-images.githubusercontent.com/84621585/135844957-cdc4acaa-77d4-4c42-8643-55b794f37fa7.png)
g?
